# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.0.0-beta.2
group=com.github.iunius118.laserbladetools
java_version=25

# Common
minecraft_version=26.1.2
mod_name=LaserBlade-Tools
mod_author=Iunius118
mod_id=laserbladetools
license=MIT License
credits=Created by Iunius118.
description=Adds laser blade tools.
minecraft_version_range=[26.1.2, 26.2)
neo_form_version=26.1.2-1

# Fabric
fabric_version=0.149.0+26.1.2
fabric_loader_version=0.19.2
cloth_config_version=26.1.154

# Forge
forge_version=64.0.8
forge_loader_version_range=[64,)

# NeoForge
neoforge_version=26.1.2.50-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
